---
name: "Run Container Scan on Super Mario Docker Image with Quality Gate"

on:
  push:
    branches:
      - main

env:
  VERSION: $(( $(cat version.txt) + 1 ))

jobs:

  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Get Docker Image from Docker Hub
        shell: bash -eux {0}
        run: |
          docker pull docker.io/aquarellfantasiagithub/eriksprojectrepo:${{ env.VERSION }}
          docker save -o /github/workspace/supermariolatestdockerimage.tar docker.io/aquarellfantasiagithub/eriksprojectrepo:${{ env.VERSION }}

      - name: Validate docker image exists
        shell: bash -eux {0}
        run: |
          if [ ! -f /github/workspace/supermariolatestdockerimage.tar ]; then
            echo "Docker image does not exist"
            exit 1
          fi

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
